steps:
  # Build frontend
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', 'flask-example/']
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend']
#Deploy to GKE
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'
# step 4  use the name of the container image that you specify in Deployment when updating the image
# Do not specify tag or latest and it will always check gcr for latest then pull image.
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment/frontend',  
   'frontend-demo=gcr.io/$PROJECT_ID/frontend'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'
images:
- gcr.io/$PROJECT_ID/frontend

# Deploy container image to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['beta', 'run', 'deploy', 'frontend', '--image', 'gcr.io/$PROJECT_ID/frontend', '--cluster','gke-advance', '--cluster-location', 'us-central1-a']