steps:
  # Step 1 Knative build
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'knative/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'
images:
- gcr.io/$PROJECT_ID/frontend-knative